### PR TITLE
- Change H-A component from Light to LightEntity

### PR DESCRIPTION
**Pull request by GreenTentacle**
Starting with Home-Assistant .110 a message appears to update the component from Light to LightEntity due to deprecation

### CODE REVIEW

**Comment by BazaJayGee66** [comment]
Yup, nice catch.
This looks to be a breaking change, and people will need to upgrade HA to 0.110.*

**Comment by GreenTentacle** [comment]
The `except` clause I put in should allow using the old-style `Light` if the `LightEntity` can't be imported.  This is the way another custom component I looked at does it.

**Comment by GreenTentacle** [comment]
I could probably handle it more precisely with a 

```
except ImportError:
``` 

instead.

**Comment by BazaJayGee66** [comment]
Ahh awesome, sorry totally missed it was in a try block

**Comment by NoedelVreter** [comment]
Thanks!

**Pull request merged**
